######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 2.4  89/01/10  23:32:22  gm0w
# 	Forgot trailing / on IDIR.
# 	[89/01/10            gm0w]
# 
# Revision 2.3  89/01/10  23:27:21  gm0w
# 	Forgot to quote hash sign.
# 	[89/01/10            gm0w]
# 
# Revision 2.2  89/01/10  23:17:56  gm0w
# 	Created.
# 	[89/01/10            gm0w]
# 
######################################################################

IDIR			= /usr/misc/.sdm/lib/project/

BUILD_HERE		=

SED_OPTIONS		= -e '/^\#/d'

IMODE			= 644

include ../../../../../Makefile-common
