######################################################################
# HISTORY
#  9-Jan-89  Paul Parker (parker) at Carnegie-Mellon University
#	Created for new and improved SSP.
#
# $Log:	Makefile,v $
# Revision 2.0  89/06/15  16:37:21  dimitris
#   Organized into a misc collection and SSPized
# 
# 
######################################################################

%:
	@echo "Need ${MACHINE}/Makefile for libnfs!"
