######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 2.4  88/11/08  19:48:12  gm0w
# 	Created for new and improved SSP format.
# 	[88/10/23            gm0w]
# 
######################################################################

IDIR			= /usr/cs/

BUILD_HERE		=

include ../../Makefile-common
