######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 2.3  88/11/09  00:36:25  gm0w
# 	Created for new and improved SSP format.
# 	[88/10/23            gm0w]
# 
######################################################################

IDIR			= /usr/misc/.sdm/man/

BUILD_HERE		=

IMODE			= 444

include ../../../../Makefile-common
