######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 1.11  88/11/08  20:43:13  gm0w
# 	Created for new and improved SSP format.
# 	[88/10/23            gm0w]
# 
######################################################################

%:
	@echo "Need ${MACHINE}/Makefile for libc!"
