######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 2.8  89/06/18  14:44:29  gm0w
# 	Removed moduki link to modkernel and release_SED_OPTIONS.
# 	[89/06/18            gm0w]
# 
# Revision 2.7  89/06/08  14:38:22  gm0w
# 	Removed makedist target.
# 	[89/06/08            gm0w]
# 
# Revision 2.6  89/01/09  11:02:49  dlc
# 	Added mode for mmdfaliases.awk script.
# 	[89/01/09  10:57:30  dlc]
# 
# Revision 2.5  88/11/08  20:11:35  gm0w
# 	Created for new and improved SSP format.
# 	[88/10/23            gm0w]
# 
######################################################################

IDIR			= /usr/cs/etc/

BUILD_HERE		=

dosyssup_IGROUP		= admin
dosyssup_IMODE		= 4750
dosyssup_IOWNER		= root
killjog.cnfg_IMODE	= 644
la_IMODE		= 711
la_LIBS			= -lsys
modkernel_IGROUP	= admin
modkernel_IMODE		= 4750
modkernel_IOWNER	= root
modmisc_IGROUP		= admin
modmisc_IMODE		= 4750
modmisc_IOWNER		= root
ostalk_IGROUP		= opr
ostalk_IMODE		= 4710
ostalk_IOWNER		= root
rfs_LIBS		= -lsys
rfshost_LIBS		= -lsys
rfslink_IMODE		= 4711
rfslink_IOWNER		= root
transopt_IGROUP		= opr
transopt_IMODE		= 4710
transopt_IOWNER		= root
ttyatt_IGROUP		= opr
ttyatt_IMODE		= 6710
ttyatt_IOWNER		= root
ttyatt_LIBS		= -lsys
version_IGROUP		= kmem
version_IMODE		= 2711
vmnlist.list_IMODE	= 644
mmdfaliases.awk_IMODE	= 644

include ../../../Makefile-common
