######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 1.8  88/11/08  20:37:00  gm0w
# 	Created for new and improved SSP format.
# 	[88/10/23            gm0w]
# 
######################################################################

IDIR			= /usr/cs/lib/

BUILD_HERE		=

IMODE			= 644

cbupdate_IMODE		= 4711
cbupdate_IOWNER		= root
bb-alias_IMODE		= 755
ml-alias_IMODE		= 755

include ../../../Makefile-common
