#####################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 2.0  89/06/15  16:32:08  dimitris
#   Organized into a misc collection and SSPized
# 
#####################################################

IDIR	=	/usr/misc/.nfs/lib

SUBDIRS		=	libnfs librpc librpcsvc

DATAFILES	=	

IMODE		=	644

include ../../../../Makefile-common
