# HISTORY
# $Log:	Makefile,v $
# Revision 2.0  89/06/15  15:26:13  dimitris
#   Organized into a misc collection and SSPized
# 
#

IDIR	=	/usr/misc/.nfs/

DATAFILES = rc.nfs

SUBDIRS		= lib etc 

include ../../../Makefile-common
