######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 2.3  89/01/28  23:20:50  gm0w
# 	Updated to new SSP format.
# 	[89/01/28            gm0w]
# 
# Revision 2.2  88/10/13  17:55:21  mja
# 	Created.
# 
######################################################################

IDIR			= /usr/misc/.sdm/

BUILD_HERE		=

include ../../../Makefile-common
