######################################################################
# HISTORY
# $Log:	Makefile,v $
# Revision 2.2  89/01/18  15:19:46  parker
# 	Created for new and improved SSP.
# 	[88/12/21            parker]
# 
######################################################################

%:
	@echo "dbx may only be made for the VAX,IBMRT, and SUN"
