######################################################################
# HISTORY
# 25-Aug-89  Mary Thompson (mrt) at Carnegie-Mellon University
#	Short version for Mach 2.5 release
#
# $Log:	Makefile,v $
# Revision 2.2  88/09/10  20:26:55  mja
# 	Created.
# 	[88/09/08  22:54:09  mja]
# 
######################################################################

IDIR			= /usr/

SUBDIRS			=  cs misc ucb

include ../Makefile-common
